services:
  esp-idf:
    image: espressif/idf:v5.2
    container_name: bomba_esp_idf
    working_dir: /workspace
    volumes:
      - .:/workspace
      - /dev:/dev
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - IDF_TARGET=esp32
    stdin_open: true
    tty: true
    privileged: true
